### ISSUE TITLE
EPIC CHECKLIST: Review/Integrate staged deposit-only ref impl work

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#119]
In the `staging` branch you can find a `opnode` dir with the reference implementation for the deposit-only milestone.
You can run it end-to-end with [these instructions](https://github.com/protolambda/rollup-node-experiments/).

To simplify review, clean up the commit history, and help organize, we can split the staging branch into indepdent PRs:
- [x] `opnode/cmd` + Go CI + go.sum file: boring boilerplate to run it as binary + CI setup, minimum compiling Go:
  #124
- [x] `opnode/eth`: API interfaces, api utils and types:
  #125
- [x] `opnode/l1`: parallized/cached blocks and receipts downloader with tests:
  #126
- [x] `opnode/l2/api.go`: Execution Engine API client bindings:
  #127
- [x] `opnode/l2/{reading.go, input_derivation.go}`: convert block/receipts (interfaces for mocking in tests) to deposit transactions:
  #128
- [x] `opnode/l2/{output_derivation.go, driver_step.go}`: where the we derive outputs and apply the block to the engine:
  #129
- [x] `opnode/l2/{sync_reference.go, sync_start.go}`: how we resolve where sync needs to start:
  #130
- [x] `opnode/l2/driver.go`: the main event system of engine sync:
  #131
- [x] `opnode/node/`: rollup-node start (init, manage and shut down all L1 and L2 processes):
  #132

**Comment by protolambda** [comment]
completed all PRs, closing this
