### ISSUE TITLE
Milestone epic: Withdrawals

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#157]
Validates withdrawals based on block-header proofs from the Block Oracle, and transaction receipt proofs.

Includes plans for upgrading the Bridge contracts.

Includes optimizing cost of withdrawals (in consultation with Integrations).

- [ ] Review existing withdrawal implementation:
  - Very large amount of internal/external stakeholders to involve in the design discussion 
  - Maybe we need a grace period where we post both state-root and new merkleized approach, to ease into the improved version?
- Spec (see https://github.com/ethereum-optimism/optimistic-specs/issues/100):
  - [ ] Define withdrawal format
    - Review compatibility with existing withdrawals
    - Optimized ETH/token withdrawals?
    - Utilize the new merkleized structure for cheap withdrawal proofs instead of complicated state reads
  - [ ] Define withdrawal receipt format (EVM withdrawal log is converted to SSZ withdrawal receipt,
    and merkleized into the withdrawal tree that the proposer commits to)
  - [ ] Define withdrawal predeploy contract (emit log when sending tokens/ETH to withdraw)
- Contracts
  - Implement L2 withdrawal predeploy
- Rollup node:
  - Compute the withdrawal trie root from receipts after updating the block
    - TODO: extra post-EVM computation is far from ideal. 
      At higher withdrawal cost we could track the withdrawal-tree inside of the EVM with a merkle-stack.
      Then the user can call `view` contract function to compute the latest withdrawal-trie root at any time.
  - Verify withdrawal-trie (update "L2 root commitment" verification)
