### ISSUE TITLE
Milestone epic: Gas Golfed Deposit

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#158]
Modifications to the DepositFeed contract. 
Will likely impact the format of the emitted event meaning the rollup node will need to be updated to.

- [ ] Gas golf setup: hybrid approach with foundry and hard-hat?
- [ ] Gas golf the deposit function and receipt format (see issue https://github.com/ethereum-optimism/optimistic-specs/issues/134):
  - less memory
  - less calldata
  - single SSTORE/SLOAD for EIP-1559 fee updates (see deposit fees discussion)
  - optimized receipt encoding
- [ ] Updated deposit-only release for testing
