### ISSUE TITLE
Milestone epic: Sequencing

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#160]
A client mode which accepts transactions directly, 
returns the result of execution, and generates a new Sequencer block.

Introduces sequencer blocks, and batch submission.

- Spec updates
  - [x] #183 (work in progress) (TODO 1)
  - [x] #184 (low priority)
- Contract updates
  - [x] #192 (see draft #196)
- Rollup-node updates
  - [x] #185 (see #202)
  - [x] #187 (TODO 3: downloader split)
  - [x] #189 (TODO 2: batch parsing)
  - [x] #190 (low priority)
  - [x] #191 (TODO 4: seq window delay in sync start point if not sequencer)
    - Reorg away from sequencer blocks that overflow the sequencer window instead of new window: enforce deposit inclusion
- Sequencer updates, extension of rollup-node:
  - [x] Simple mode (TODO 5): call engine API and construct sequencer block from L2 geth transaction pool (like L1 does by default)
    - [x] Update [reference-optimistic-geth](https://github.com/ethereum-optimism/reference-optimistic-geth/) engine 
      API to accept transactions and continue building of the block with the tx-pool.
  - ~~Advanced mode: port over transaction-queue from pre-1.0 node, to sequence blocks with transactions that were accepted through the RPC~~ (low priority, tx pools + 2 second block time may be enough, and this advanced mode conflicts with distributed sequencer milestone)

Sequencer implementation checklist:
- [x] Update driver to trigger new block building if fully synced
  - sync remaining window batches, i.e. ensure all L1 batches are accounted for even when sequencing window is not finished yet
- [x] Update L1 target-epoch that the sequencer targets when including new deposits
  - tracked in driver state, encoded in batch
- [x] Prepare payload as sequencer
  - Repeat latest forkchoice update, with payload attributes, and transactions flag set to pull from engine tx pool
- [x] In driver loop: time end of slot time, pull prepared payload
- [x] Execute and update forkchoice to persist payload
- [x] Convert to batch and compress for batch submission
- [x] Placeholder for p2p/other block distribution on L2

**Comment by norswap** [comment]
adding myself for the spec part

**Comment by maurelian** [comment]
> adding myself for the spec part

Assignee on this issue means owning the milestone. It will be broken up in to smaller issues which will be assigned accordingly.

**Comment by protolambda** [comment]
I'll create issues for the sub-tasks, track them here, and assign others to them. But first priority is the L2 output commitment work, so this issue will be inactive this week.

**Comment by norswap** [comment]
@tynes I'm really not sure that it's the best solution in this case.

From what I gather they made the decision to process withdrawal as a "system action" on L1 (like a miner reward), with the alternative being a special transaction type.

I think they would have come to a very different conclusion if these transactions actually had to be executed, like we have to execute deposited transactions.

Just consider for instance the receipts emitted for these transactions. If we store deposited transactions separately from other transactions, then we lose this mapping that there is one receipt per transaction, and thus the receipt array is as big as the transaction array etc.

So I have the intuition that keeping the new deposit transaction type keeps the diff with upstream geth more minimal.

**Comment by protolambda** [comment]
Closing this, sequencing milestone is done and the next work has already started.
