### ISSUE TITLE
Milestone epic: Stateless Compression of  Transaction Data

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#161]
Define or choose a compression algorithm. Benchmark it. Implement it.

- Research
  - [x] #174
    - See https://github.com/ethereum-optimism/optimistic-specs/issues/10
   - [x] #175
- Spec updates
  - [ ] Update derivation to decompress batch data (= stateless compression)
  - [ ] Update batch-submission spec to compress batch data
- Rollup-node updates
  - [ ] Update derivation code
- Rollup-node sequencer extension updates:
  - [ ] Update batch-submission to compress batch data

Note: this may be ported back to the pre-1.0 deployment and rolled out before 1.0 production release.

**Comment by ben-chain** [comment]
A note on this: since so many crypto transactions contain a large number of hashes/addresses/etc. which are "random" and hard to compress, I think a prepopulated dictionary could afford really big savings here and is worth investigating.  It could just be a stateless hardcoded thing which we upgrade once in a while.

**Comment by maurelian** [comment]
Reminds me of the caching functionality in the ds-proxy:

https://github.com/dapphub/ds-proxy/blob/master/src/proxy.sol#l130

**Comment by lucasprelancamentos** [comment]
concordo com a pontuação de que muitas transações criptográficas contêm um grande número de hashes/endereços/etc. que são "aleatórios" e difíceis de compactar, acho que um dicionário pré-preenchido poderia economizar muito aqui e vale a pena investigar. Pode ser apenas um ditado sem estado/codificado que atualizamos o binário de vez em quando.
