### ISSUE TITLE
Milestone epic: Distributed sequencer

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimistic-specs#162]
Enable backup Sequencer nodes to keep in sync with the Sequencer, and serve as a fallback and/or load balancing.

Spec & Implement:
- [ ] API to track sequencer work (transaction queue, unconfirmed but published L2 blocks)
- [ ] BFT or other backup strategy to decide on new sequencer leader node
- [ ] Recovery of sequencing state upon becoming the new leader: don't drop transactions that were accepted via RPC previously
- [ ] Design testing for different failure modes (crashes, load-balancing, etc.)
